/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.naturalsciences.bmdc.ears.topcomponents;

import be.naturalsciences.bmdc.ears.topcomponents.tablemodel.ProjectTableModel;
import be.naturalsciences.bmdc.ears.entities.IResponseMessage;
import be.naturalsciences.bmdc.ears.infobar.InfoBar;
import be.naturalsciences.bmdc.ears.netbeans.services.GlobalActionContextProxy;
import be.naturalsciences.bmdc.ears.utils.Message;
import be.naturalsciences.bmdc.ears.utils.Messaging;
import be.naturalsciences.bmdc.ears.utils.TaskListener;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//be.ac.mumm//CreateProgramSetup//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CreateProgramSetupTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "be.naturalsciences.bmdc.ears.topcomponents.CreateProgramSetupTopComponent")
@ActionReferences({
    // @ActionReference(path = "Toolbars/Window", position = 3333,name = "Create new program"),
    @ActionReference(path = "Menu/Window/Cruise & program setup", position = 2)
})

@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CreateProgramSetupAction",
        preferredID = "CreateProgramSetupTopComponent"
)
@Messages({
    "CTL_CreateProgramSetupAction=Create new program...",
    "CTL_CreateProgramSetupTopComponent=Create new program",
    "HINT_CreateProgramSetupTopComponent=Create a new program by choosing cruise, PI,..."
})
public final class CreateProgramSetupTopComponent extends AbstractProgramTopComponent implements TaskListener {

    public CreateProgramSetupTopComponent() {
        super();
        setName(Bundle.CTL_CreateProgramSetupTopComponent());
        setToolTipText(Bundle.HINT_CreateProgramSetupTopComponent());

        super.addProject = addProject;
        super.collateCentreListPrincipal = collateCentreListPrincipal;
        super.collateCentreListSecondary = collateCentreListSecondary;
        super.cruiseComboBox = cruiseComboBox;
        super.jPanel1 = jPanel1;
        super.jPanel2 = jPanel2;
        super.jPanelCollateCentre = jPanelCollateCentre;
        super.jScrollPane1 = jScrollPane1;
        super.jScrollPane2 = jScrollPane2;
        super.jScrollPane3 = jScrollPane3;
        super.o_collateCentreResult = o_collateCentreResult;
        super.o_description = o_description;
        super.o_piName = o_piName;
        super.o_programId_Attribut = o_programId_Attribut;
        super.programIdentifier = programIdentifier;
        super.programIdentifier1 = programIdentifier1;
        super.programIdentifier3 = programIdentifier3;
        super.programIdentifier4 = programIdentifier4;
        super.projectEdmerpTable = projectEdmerpTable;
        super.removeProject = removeProject;

        populateCruiseCombobox();
    }

    @Override
    protected void __initComponents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        programIdentifier = new javax.swing.JPanel();
        cruiseComboBox = new javax.swing.JComboBox();
        programIdentifier1 = new javax.swing.JPanel();
        o_programId_Attribut = new javax.swing.JTextField();
        programIdentifier3 = new javax.swing.JPanel();
        o_piName = new javax.swing.JTextField();
        programIdentifier4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        o_description = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        addProject = new javax.swing.JButton();
        removeProject = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projectEdmerpTable = new javax.swing.JTable();
        jPanelCollateCentre = new javax.swing.JPanel();
        collateCentreListPrincipal = new javax.swing.JComboBox();
        collateCentreListSecondary = new javax.swing.JComboBox();
        o_collateCentreResult = new javax.swing.JTextField();
        o_saveProgram = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        jPanel1.setMinimumSize(new java.awt.Dimension(27, 27));
        jPanel1.setPreferredSize(new java.awt.Dimension(1278, 642));

        programIdentifier.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programIdentifier.border.title"))); // NOI18N

        cruiseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cruiseComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programIdentifierLayout = new javax.swing.GroupLayout(programIdentifier);
        programIdentifier.setLayout(programIdentifierLayout);
        programIdentifierLayout.setHorizontalGroup(
            programIdentifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cruiseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programIdentifierLayout.setVerticalGroup(
            programIdentifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programIdentifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cruiseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programIdentifier1.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programIdentifier1.border.title"))); // NOI18N

        o_programId_Attribut.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_programId_Attribut.text")); // NOI18N
        o_programId_Attribut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_programId_AttributActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programIdentifier1Layout = new javax.swing.GroupLayout(programIdentifier1);
        programIdentifier1.setLayout(programIdentifier1Layout);
        programIdentifier1Layout.setHorizontalGroup(
            programIdentifier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifier1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_programId_Attribut, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programIdentifier1Layout.setVerticalGroup(
            programIdentifier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(o_programId_Attribut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        programIdentifier3.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programIdentifier3.border.title"))); // NOI18N

        o_piName.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_piName.text")); // NOI18N
        o_piName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_piNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programIdentifier3Layout = new javax.swing.GroupLayout(programIdentifier3);
        programIdentifier3.setLayout(programIdentifier3Layout);
        programIdentifier3Layout.setHorizontalGroup(
            programIdentifier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifier3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_piName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programIdentifier3Layout.setVerticalGroup(
            programIdentifier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programIdentifier3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(o_piName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programIdentifier4.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programIdentifier4.border.title"))); // NOI18N

        o_description.setColumns(20);
        o_description.setRows(5);
        jScrollPane2.setViewportView(o_description);

        javax.swing.GroupLayout programIdentifier4Layout = new javax.swing.GroupLayout(programIdentifier4);
        programIdentifier4.setLayout(programIdentifier4Layout);
        programIdentifier4Layout.setHorizontalGroup(
            programIdentifier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifier4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        programIdentifier4Layout.setVerticalGroup(
            programIdentifier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.jPanel2.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addProject, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.addProject.text")); // NOI18N
        addProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeProject, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.removeProject.text")); // NOI18N
        removeProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProjectActionPerformed(evt);
            }
        });

        projectEdmerpTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        projectEdmerpTable.setModel(new ProjectTableModel());
        projectEdmerpTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectEdmerpTableFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(projectEdmerpTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProject, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeProject))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addProject)
                        .addGap(18, 18, 18)
                        .addComponent(removeProject))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelCollateCentre.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCollateCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.jPanelCollateCentre.border.title"))); // NOI18N

        collateCentreListPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collateCentreListPrincipalActionPerformed(evt);
            }
        });

        collateCentreListSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collateCentreListSecondaryActionPerformed(evt);
            }
        });

        o_collateCentreResult.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_collateCentreResult.text")); // NOI18N
        o_collateCentreResult.setEnabled(false);
        o_collateCentreResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_collateCentreResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCollateCentreLayout = new javax.swing.GroupLayout(jPanelCollateCentre);
        jPanelCollateCentre.setLayout(jPanelCollateCentreLayout);
        jPanelCollateCentreLayout.setHorizontalGroup(
            jPanelCollateCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCollateCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(collateCentreListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(collateCentreListSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o_collateCentreResult, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelCollateCentreLayout.setVerticalGroup(
            jPanelCollateCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCollateCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(collateCentreListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(collateCentreListSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(o_collateCentreResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(o_saveProgram, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_saveProgram.text")); // NOI18N
        o_saveProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_saveProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o_saveProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(programIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(programIdentifier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(programIdentifier3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCollateCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(programIdentifier4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(o_saveProgram)
                    .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programIdentifier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programIdentifier3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCollateCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programIdentifier4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cruiseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cruiseComboBoxActionPerformed
        // TODO add your handling code here:
        super.cruiseComboBoxActionPerformedP(evt);

    }//GEN-LAST:event_cruiseComboBoxActionPerformed

    private void projectEdmerpTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectEdmerpTableFocusLost
        // TODO add your handling code here:
        super.projectEdmerpTableFocusLostP(evt);
    }//GEN-LAST:event_projectEdmerpTableFocusLost

    private void addProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectActionPerformed
        super.addProjectActionPerformedP(evt);

    }//GEN-LAST:event_addProjectActionPerformed

    private void removeProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProjectActionPerformed
        super.removeProjectActionPerformedP(evt);
    }//GEN-LAST:event_removeProjectActionPerformed

    private void collateCentreListPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collateCentreListPrincipalActionPerformed
        super.collateCentreListPrincipalActionPerformedP(evt);
    }//GEN-LAST:event_collateCentreListPrincipalActionPerformed

    private void collateCentreListSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collateCentreListSecondaryActionPerformed
        super.collateCentreListSecondaryActionPerformedP(evt);
    }//GEN-LAST:event_collateCentreListSecondaryActionPerformed

    private void o_collateCentreResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_collateCentreResultActionPerformed
        // TODO add your handling code here:
        super.o_collateCentreResultActionPerformedP(evt);
    }//GEN-LAST:event_o_collateCentreResultActionPerformed

    private void o_piNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_piNameActionPerformed
        // TODO add your handling code here:
        super.o_piNameActionPerformedP(evt);
    }//GEN-LAST:event_o_piNameActionPerformed

    private void o_saveProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_saveProgramActionPerformed
        // TODO add your handling code here:

        /*int nRowSeaArea = projectTableModel.getRowCount();
         for (int i = 0; i < nRowSeaArea; i++) {
         System.out.println(projectTableModel.getValueAt(i, 3).toString());
         collectionProjects.add(new Projects(projectTableModel.getValueAt(i, 3).toString(), projectTableModel.getValueAt(i, 3).toString()));//ok 
         }
         program.setProjects(collectionProjects);*/
        /*try {
         RestClientProgram client = new RestClientProgram();
         client.postProgram(program);
         //le serveur renvoie le message 200 ok mais un probleme avec seaarea ?? : voir le debug il me renvoie une erreur 500 ??? internal server error => Oscar for more

         this.close();// close TopComponent IF no exception
         io.getOut().println("Record added \n See result on ");
         } catch (Exception e) {
         io.getOut().println("exception" + e.toString());
         }*/
        postProgram();
    }//GEN-LAST:event_o_saveProgramActionPerformed

    private void o_programId_AttributActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_programId_AttributActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_programId_AttributActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProject;
    private javax.swing.JComboBox collateCentreListPrincipal;
    private javax.swing.JComboBox collateCentreListSecondary;
    private javax.swing.JComboBox cruiseComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCollateCentre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField o_collateCentreResult;
    private javax.swing.JTextArea o_description;
    private javax.swing.JTextField o_piName;
    private javax.swing.JTextField o_programId_Attribut;
    private javax.swing.JButton o_saveProgram;
    private javax.swing.JPanel programIdentifier;
    private javax.swing.JPanel programIdentifier1;
    private javax.swing.JPanel programIdentifier3;
    private javax.swing.JPanel programIdentifier4;
    private javax.swing.JTable projectEdmerpTable;
    private javax.swing.JButton removeProject;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        group = validationPanel1.getValidationGroup();
        super.componentOpened();

        o_saveProgram.setEnabled(false);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    ProgressHandle progr;

    private void postProgram() {
        if (formValidates()) {
            actualProgram = createProgramFromInput();
            if (actualProgram != null) {
                progr = ProgressHandleFactory.createHandle("Sending program info...");
                IResponseMessage response = null;
                AbstractProgramTopComponent.ProgramPoster tsk = new CreateProgramSetupTopComponent.ProgramPoster(progr, response);
                tsk.addListener(this);

                RequestProcessor.getDefault().post(tsk);
                progr.finish();

            }
        } else {
            Messaging.report("Form not valid. Verify it first", Message.State.BAD, this.getClass(), true);
        }
    }

    @Override
    public void checkValidation() {
        if (!formValidates()) {
            o_saveProgram.setEnabled(false);

        } else {
            o_saveProgram.setEnabled(true);
        }
    }

    @Override
    public void threadComplete(Runnable runner) {
        try {
            progr.finish();
            if (InfoBar.getInstance().noProblemsLately()) {
                //this.close();
                GlobalActionContextProxy.getInstance().add(currentCruiseResult.getCurrent()); //causes the cruise to be changed to itself, causing cruise listeners to update their program list

            }
        } catch (AssertionError | IllegalStateException e) {
            int a = 5;
        }
    }

}
