/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.naturalsciences.bmdc.ears.topcomponents;

import be.naturalsciences.bmdc.ears.topcomponents.tablemodel.ProjectTableModel;
import be.naturalsciences.bmdc.ears.entities.IResponseMessage;
import be.naturalsciences.bmdc.ears.infobar.InfoBar;
import be.naturalsciences.bmdc.ears.netbeans.services.GlobalActionContextProxy;
import be.naturalsciences.bmdc.ears.utils.Message;
import be.naturalsciences.bmdc.ears.utils.Messaging;
import be.naturalsciences.bmdc.ears.utils.TaskListener;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.util.LookupEvent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//be.ac.mumm//CreateProgramSetup//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CreateProgramSetupTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "be.naturalsciences.bmdc.ears.topcomponents.CreateProgramSetupTopComponent")
@ActionReferences({
    // @ActionReference(path = "Toolbars/Window", position = 3333,name = "Create new program"),
    @ActionReference(path = "Menu/Window/Cruise & program setup", position = 2)
})

@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CreateProgramSetupAction",
        preferredID = "CreateProgramSetupTopComponent"
)
@Messages({
    "CTL_CreateProgramSetupAction=New program",
    "CTL_CreateProgramSetupTopComponent=Create new program",
    "HINT_CreateProgramSetupTopComponent=Create a new program by choosing PI,..."
})
public final class CreateProgramSetupTopComponent extends AbstractProgramTopComponent implements TaskListener {

    public CreateProgramSetupTopComponent() {
        super();
        setName(Bundle.CTL_CreateProgramSetupTopComponent());
        setToolTipText(Bundle.HINT_CreateProgramSetupTopComponent());

        super.addProject = addProject;
        super.piOrganisationCountry = collateCentreListPrincipal;
        super.piOrganisationSecondary = collateCentreListSecondary;
        super.jPanel1 = jPanel1;
        super.jPanel2 = programProjectPanel;
        super.jPanelCollateCentre = piOrganisationPanel;
        super.jScrollPane1 = jScrollPane1;
        super.jScrollPane2 = jScrollPane2;
        super.jScrollPane3 = jScrollPane3;
        super.o_collateCentreResult = o_collateCentreResult;
        super.descriptionTextField = o_description;
        super.piFirstNameTextField = firstNameTextbox;
        super.piLastNameTextField = lastNameTextbox;
        super.programIdTextField = o_programId_Attribut;
        super.programIdentifier = programIdentifier;
        super.programIdentifier1 = programNamePanel;
        super.programIdentifier3 = piNamePanel;
        super.programIdentifier4 = programDescriptionPanel;
        super.projectEdmerpTable = projectEdmerpTable;
        super.removeProject = removeProject;
    }

    @Override
    protected void __initComponents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        programNamePanel = new javax.swing.JPanel();
        o_programId_Attribut = new javax.swing.JTextField();
        piNamePanel = new javax.swing.JPanel();
        firstNameTextbox = new javax.swing.JTextField();
        lastNameTextbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        programDescriptionPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        o_description = new javax.swing.JTextArea();
        programProjectPanel = new javax.swing.JPanel();
        addProject = new javax.swing.JButton();
        removeProject = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projectEdmerpTable = new javax.swing.JTable();
        piOrganisationPanel = new javax.swing.JPanel();
        collateCentreListPrincipal = new javax.swing.JComboBox();
        collateCentreListSecondary = new javax.swing.JComboBox();
        o_collateCentreResult = new javax.swing.JTextField();
        o_saveProgram = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        jPanel1.setMinimumSize(new java.awt.Dimension(27, 27));
        jPanel1.setPreferredSize(new java.awt.Dimension(1278, 642));

        programNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        programNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programNamePanel.border.title"))); // NOI18N
        programNamePanel.setPreferredSize(new java.awt.Dimension(695, 45));

        o_programId_Attribut.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_programId_Attribut.text")); // NOI18N
        o_programId_Attribut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_programId_AttributActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programNamePanelLayout = new javax.swing.GroupLayout(programNamePanel);
        programNamePanel.setLayout(programNamePanelLayout);
        programNamePanelLayout.setHorizontalGroup(
            programNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_programId_Attribut, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        programNamePanelLayout.setVerticalGroup(
            programNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(o_programId_Attribut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        piNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        piNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.piNamePanel.border.title"))); // NOI18N
        piNamePanel.setPreferredSize(new java.awt.Dimension(695, 45));

        firstNameTextbox.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.firstNameTextbox.text")); // NOI18N
        firstNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextboxActionPerformed(evt);
            }
        });

        lastNameTextbox.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.lastNameTextbox.text")); // NOI18N
        lastNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextboxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout piNamePanelLayout = new javax.swing.GroupLayout(piNamePanel);
        piNamePanel.setLayout(piNamePanelLayout);
        piNamePanelLayout.setHorizontalGroup(
            piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piNamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        piNamePanelLayout.setVerticalGroup(
            piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piNamePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(piNamePanelLayout.createSequentialGroup()
                    .addGroup(piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lastNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programDescriptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        programDescriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programDescriptionPanel.border.title"))); // NOI18N

        o_description.setColumns(20);
        o_description.setRows(5);
        jScrollPane2.setViewportView(o_description);

        javax.swing.GroupLayout programDescriptionPanelLayout = new javax.swing.GroupLayout(programDescriptionPanel);
        programDescriptionPanel.setLayout(programDescriptionPanelLayout);
        programDescriptionPanelLayout.setHorizontalGroup(
            programDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programDescriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programDescriptionPanelLayout.setVerticalGroup(
            programDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        programProjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        programProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programProjectPanel.border.title"))); // NOI18N
        programProjectPanel.setToolTipText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.programProjectPanel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addProject, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.addProject.text")); // NOI18N
        addProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeProject, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.removeProject.text")); // NOI18N
        removeProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProjectActionPerformed(evt);
            }
        });

        projectEdmerpTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        projectEdmerpTable.setModel(new ProjectTableModel());
        projectEdmerpTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectEdmerpTableFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(projectEdmerpTable);

        javax.swing.GroupLayout programProjectPanelLayout = new javax.swing.GroupLayout(programProjectPanel);
        programProjectPanel.setLayout(programProjectPanelLayout);
        programProjectPanelLayout.setHorizontalGroup(
            programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProject, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeProject))
                .addContainerGap())
        );
        programProjectPanelLayout.setVerticalGroup(
            programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programProjectPanelLayout.createSequentialGroup()
                .addComponent(addProject)
                .addGap(18, 18, 18)
                .addComponent(removeProject)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        piOrganisationPanel.setBackground(new java.awt.Color(255, 255, 255));
        piOrganisationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.piOrganisationPanel.border.title"))); // NOI18N

        collateCentreListPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collateCentreListPrincipalActionPerformed(evt);
            }
        });

        collateCentreListSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collateCentreListSecondaryActionPerformed(evt);
            }
        });

        o_collateCentreResult.setText(org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_collateCentreResult.text")); // NOI18N
        o_collateCentreResult.setEnabled(false);
        o_collateCentreResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_collateCentreResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout piOrganisationPanelLayout = new javax.swing.GroupLayout(piOrganisationPanel);
        piOrganisationPanel.setLayout(piOrganisationPanelLayout);
        piOrganisationPanelLayout.setHorizontalGroup(
            piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piOrganisationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(piOrganisationPanelLayout.createSequentialGroup()
                        .addComponent(o_collateCentreResult, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(piOrganisationPanelLayout.createSequentialGroup()
                        .addGroup(piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(collateCentreListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(collateCentreListSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        piOrganisationPanelLayout.setVerticalGroup(
            piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piOrganisationPanelLayout.createSequentialGroup()
                .addComponent(collateCentreListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collateCentreListSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o_collateCentreResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(o_saveProgram, org.openide.util.NbBundle.getMessage(CreateProgramSetupTopComponent.class, "CreateProgramSetupTopComponent.o_saveProgram.text")); // NOI18N
        o_saveProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_saveProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(piNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(programNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(o_saveProgram)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(piOrganisationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(programDescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(programProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(576, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o_saveProgram)
                    .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piOrganisationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programDescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void o_saveProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_saveProgramActionPerformed
        // TODO add your handling code here:

        /*int nRowSeaArea = projectTableModel.getRowCount();
        for (int i = 0; i < nRowSeaArea; i++) {
            System.out.println(projectTableModel.getValueAt(i, 3).toString());
            collectionProjects.add(new Projects(projectTableModel.getValueAt(i, 3).toString(), projectTableModel.getValueAt(i, 3).toString()));//ok
        }
        program.setProjects(collectionProjects);*/
 /*try {
            RestClientProgram client = new RestClientProgram();
            client.postProgram(program);
            //le serveur renvoie le message 200 ok mais un probleme avec seaarea ?? : voir le debug il me renvoie une erreur 500 ??? internal server error => Oscar for more

            this.close();// close TopComponent IF no exception
            io.getOut().println("Record added \n See result on ");
        } catch (Exception e) {
            io.getOut().println("exception" + e.toString());
        }*/
        postProgram();
    }//GEN-LAST:event_o_saveProgramActionPerformed

    private void o_collateCentreResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_collateCentreResultActionPerformed
        // TODO add your handling code here:
        super.o_collateCentreResultActionPerformedP(evt);
    }//GEN-LAST:event_o_collateCentreResultActionPerformed

    private void collateCentreListSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collateCentreListSecondaryActionPerformed
        super.collateCentreListSecondaryActionPerformedP(evt);
    }//GEN-LAST:event_collateCentreListSecondaryActionPerformed

    private void collateCentreListPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collateCentreListPrincipalActionPerformed
        super.collateCentreListPrincipalActionPerformedP(evt);
    }//GEN-LAST:event_collateCentreListPrincipalActionPerformed

    private void projectEdmerpTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectEdmerpTableFocusLost
        // TODO add your handling code here:
        super.projectEdmerpTableFocusLostP(evt);
    }//GEN-LAST:event_projectEdmerpTableFocusLost

    private void removeProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProjectActionPerformed
        super.removeProjectActionPerformedP(evt);
    }//GEN-LAST:event_removeProjectActionPerformed

    private void addProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectActionPerformed
        super.addProjectActionPerformedP(evt);
    }//GEN-LAST:event_addProjectActionPerformed

    private void firstNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextboxActionPerformed
        // TODO add your handling code here:
        super.o_piNameActionPerformedP(evt);
    }//GEN-LAST:event_firstNameTextboxActionPerformed

    private void o_programId_AttributActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_programId_AttributActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_programId_AttributActionPerformed

    private void lastNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProject;
    private javax.swing.JComboBox collateCentreListPrincipal;
    private javax.swing.JComboBox collateCentreListSecondary;
    private javax.swing.JTextField firstNameTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameTextbox;
    private javax.swing.JTextField o_collateCentreResult;
    private javax.swing.JTextArea o_description;
    private javax.swing.JTextField o_programId_Attribut;
    private javax.swing.JButton o_saveProgram;
    private javax.swing.JPanel piNamePanel;
    private javax.swing.JPanel piOrganisationPanel;
    private javax.swing.JPanel programDescriptionPanel;
    private javax.swing.JPanel programNamePanel;
    private javax.swing.JPanel programProjectPanel;
    private javax.swing.JTable projectEdmerpTable;
    private javax.swing.JButton removeProject;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        group = validationPanel1.getValidationGroup();
        super.componentOpened();
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    ProgressHandle progr;

    private void postProgram() {
        if (formValidates()) {
            actualProgram = createProgramFromInput();
            if (actualProgram != null) {
                progr = ProgressHandleFactory.createHandle("Sending program info...");
                IResponseMessage response = null;
                AbstractProgramTopComponent.ProgramPoster tsk = new CreateProgramSetupTopComponent.ProgramPoster(progr, response);
                tsk.addListener(this);

                RequestProcessor.getDefault().post(tsk);
                progr.finish();

            }
        } else {
            Messaging.report("Form not valid. Verify it first", Message.State.BAD, this.getClass(), true);
        }
    }

    @Override
    public void checkValidation() {
        if (!formValidates()) {
            o_saveProgram.setEnabled(false);

        } else {
            o_saveProgram.setEnabled(true);
        }
    }

    @Override
    public void threadComplete(Runnable runner) {
        progr.finish();
    }

    @Override
    public void resultChanged(LookupEvent arg0) {
    }

}
