/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.naturalsciences.bmdc.ears.topcomponents;

import be.naturalsciences.bmdc.ears.topcomponents.tablemodel.ProjectTableModel;
import be.naturalsciences.bmdc.ears.entities.CruiseBean;
import be.naturalsciences.bmdc.ears.entities.IResponseMessage;
import be.naturalsciences.bmdc.ears.entities.ProgramBean;
import be.naturalsciences.bmdc.ears.infobar.InfoBar;
import be.naturalsciences.bmdc.ears.utils.Message;
import be.naturalsciences.bmdc.ears.utils.Messaging;
import be.naturalsciences.bmdc.ears.utils.TaskListener;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//be.ac.mumm//EditProgramSetup//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EditProgramSetupTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER//ys
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "be.naturalsciences.bmdc.ears.topcomponents.EditProgramSetupTopComponent")
/*ys @ActionReference(path = "Menu/Window" , position = 3)*/

@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EditProgramSetupAction",
        preferredID = "EditProgramSetupTopComponent"
)
@Messages({
    "CTL_EditProgramSetupAction=Edit Program",
    "CTL_EditProgramSetupTopComponent=EditProgramSetup Window",
    "HINT_EditProgramSetupTopComponent=This is a EditProgramSetup window"
})
public final class EditProgramSetupTopComponent extends AbstractProgramTopComponent implements TaskListener {

    private Lookup lookup;

    private static EditProgramSetupTopComponent instance;

    public EditProgramSetupTopComponent(ProgramBean program) {
        this();
        lookup = Lookups.singleton(program);
        this.actualProgram = program;
    }

    private EditProgramSetupTopComponent() {
        super();
        setName(Bundle.CTL_CreateProgramSetupTopComponent());
        setToolTipText(Bundle.HINT_CreateProgramSetupTopComponent());

        super.addProject = addProject;

        super.collateCentreListPrincipal = originatorListPrincipal;
        super.collateCentreListSecondary = originatorListSecondary;
        super.cruiseComboBox = o_cruiseId;
        super.jPanel1 = jPanel1;
        super.jPanel2 = jPanel2;
        super.jPanelCollateCentre = jPanelCollateCentre;
        super.jScrollPane1 = jScrollPane1;
        super.jScrollPane2 = jScrollPane2;
        super.jScrollPane3 = jScrollPane3;
        super.o_collateCentreResult = o_originatorCode;
        super.o_description = o_description;
        super.o_piName = o_principalInvestigator;
        super.o_programId_Attribut = o_programId;
        super.programIdentifier = programIdentifier;
        super.programIdentifier1 = programIdentifier1;
        super.programIdentifier3 = programIdentifier3;
        super.programIdentifier4 = programIdentifier4;
        super.projectEdmerpTable = projectEdmerpTable;
        super.removeProject = removeProject;

        populateCruiseCombobox();
        instance = this;
    }

    @Override
    protected void __initComponents() {
        initComponents();
    }

    @Override
    public Lookup getLookup() {
        return lookup;
    }

    public static EditProgramSetupTopComponent getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addProject = new javax.swing.JButton();
        removeProject = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projectEdmerpTable = new javax.swing.JTable();
        programIdentifier1 = new javax.swing.JPanel();
        o_programId = new javax.swing.JTextField();
        programIdentifier = new javax.swing.JPanel();
        o_cruiseId = new javax.swing.JComboBox();
        jPanelCollateCentre = new javax.swing.JPanel();
        originatorListPrincipal = new javax.swing.JComboBox();
        originatorListSecondary = new javax.swing.JComboBox();
        o_originatorCode = new javax.swing.JTextField();
        programIdentifier3 = new javax.swing.JPanel();
        o_principalInvestigator = new javax.swing.JTextField();
        programIdentifier4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        o_description = new javax.swing.JTextArea();
        bt_editCruise = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.jPanel2.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addProject, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.addProject.text")); // NOI18N
        addProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeProject, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.removeProject.text")); // NOI18N
        removeProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProjectActionPerformed(evt);
            }
        });

        projectEdmerpTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        projectEdmerpTable.setModel(new ProjectTableModel());
        projectEdmerpTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectEdmerpTableFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(projectEdmerpTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProject, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeProject))
                .addGap(8, 8, 8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeProject)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        programIdentifier1.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programIdentifier1.border.title"))); // NOI18N

        o_programId.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.o_programId.text")); // NOI18N
        o_programId.setEnabled(false);
        o_programId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_programIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programIdentifier1Layout = new javax.swing.GroupLayout(programIdentifier1);
        programIdentifier1.setLayout(programIdentifier1Layout);
        programIdentifier1Layout.setHorizontalGroup(
            programIdentifier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifier1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_programId, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programIdentifier1Layout.setVerticalGroup(
            programIdentifier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programIdentifier1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(o_programId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programIdentifier.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programIdentifier.border.title"))); // NOI18N

        o_cruiseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cruiseIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programIdentifierLayout = new javax.swing.GroupLayout(programIdentifier);
        programIdentifier.setLayout(programIdentifierLayout);
        programIdentifierLayout.setHorizontalGroup(
            programIdentifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_cruiseId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programIdentifierLayout.setVerticalGroup(
            programIdentifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programIdentifierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(o_cruiseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCollateCentre.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCollateCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.jPanelCollateCentre.border.title"))); // NOI18N

        originatorListPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originatorListPrincipalActionPerformed(evt);
            }
        });

        originatorListSecondary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originatorListSecondaryActionPerformed(evt);
            }
        });

        o_originatorCode.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.o_originatorCode.text")); // NOI18N
        o_originatorCode.setEnabled(false);
        o_originatorCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_originatorCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCollateCentreLayout = new javax.swing.GroupLayout(jPanelCollateCentre);
        jPanelCollateCentre.setLayout(jPanelCollateCentreLayout);
        jPanelCollateCentreLayout.setHorizontalGroup(
            jPanelCollateCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCollateCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originatorListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(originatorListSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(o_originatorCode, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCollateCentreLayout.setVerticalGroup(
            jPanelCollateCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCollateCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(originatorListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(originatorListSecondary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(o_originatorCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programIdentifier3.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programIdentifier3.border.title"))); // NOI18N

        o_principalInvestigator.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.o_principalInvestigator.text")); // NOI18N
        o_principalInvestigator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_principalInvestigatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programIdentifier3Layout = new javax.swing.GroupLayout(programIdentifier3);
        programIdentifier3.setLayout(programIdentifier3Layout);
        programIdentifier3Layout.setHorizontalGroup(
            programIdentifier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifier3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_principalInvestigator, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        programIdentifier3Layout.setVerticalGroup(
            programIdentifier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programIdentifier3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(o_principalInvestigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programIdentifier4.setBackground(new java.awt.Color(255, 255, 255));
        programIdentifier4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programIdentifier4.border.title"))); // NOI18N

        o_description.setColumns(20);
        o_description.setRows(5);
        jScrollPane2.setViewportView(o_description);

        javax.swing.GroupLayout programIdentifier4Layout = new javax.swing.GroupLayout(programIdentifier4);
        programIdentifier4.setLayout(programIdentifier4Layout);
        programIdentifier4Layout.setHorizontalGroup(
            programIdentifier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programIdentifier4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        programIdentifier4Layout.setVerticalGroup(
            programIdentifier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        org.openide.awt.Mnemonics.setLocalizedText(bt_editCruise, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.bt_editCruise.text")); // NOI18N
        bt_editCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editCruiseActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programIdentifier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programIdentifier4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programIdentifier3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(programIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(jPanelCollateCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editCruise, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_editCruise)
                    .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(programIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programIdentifier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(programIdentifier3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCollateCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programIdentifier4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(935, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void o_cruiseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cruiseIdActionPerformed
        // TODO add your handling code here:
        super.cruiseComboBoxActionPerformedP(evt);

    }//GEN-LAST:event_o_cruiseIdActionPerformed

    private void o_principalInvestigatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_principalInvestigatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_principalInvestigatorActionPerformed

    private void projectEdmerpTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectEdmerpTableFocusLost
        // TODO add your handling code here:
        super.projectEdmerpTableFocusLostP(evt);

    }//GEN-LAST:event_projectEdmerpTableFocusLost

    private void addProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectActionPerformed
        // TODO add your handling code here:
        super.addProjectActionPerformedP(evt);
    }//GEN-LAST:event_addProjectActionPerformed

    private void removeProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProjectActionPerformed
        // TODO add your handling code here:
        super.removeProjectActionPerformedP(evt);
    }//GEN-LAST:event_removeProjectActionPerformed

    private void originatorListPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originatorListPrincipalActionPerformed
        // TODO add your handling code here:
        super.collateCentreListPrincipalActionPerformedP(evt);
    }//GEN-LAST:event_originatorListPrincipalActionPerformed


    private void originatorListSecondaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originatorListSecondaryActionPerformed
        // TODO add your handling code here:
        super.collateCentreListSecondaryActionPerformedP(evt);
    }//GEN-LAST:event_originatorListSecondaryActionPerformed

    private void o_originatorCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_originatorCodeActionPerformed
        // TODO add your handling code here:
        super.o_collateCentreResultActionPerformedP(evt);
    }//GEN-LAST:event_o_originatorCodeActionPerformed

    private void bt_editCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editCruiseActionPerformed
        // TODO add your handling code here:
        // Show Dialog...
        postProgram();
    }//GEN-LAST:event_bt_editCruiseActionPerformed

    private void o_programIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_programIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_programIdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProject;
    private javax.swing.JButton bt_editCruise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCollateCentre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox o_cruiseId;
    private javax.swing.JTextArea o_description;
    private javax.swing.JTextField o_originatorCode;
    private javax.swing.JTextField o_principalInvestigator;
    private javax.swing.JTextField o_programId;
    private javax.swing.JComboBox originatorListPrincipal;
    private javax.swing.JComboBox originatorListSecondary;
    private javax.swing.JPanel programIdentifier;
    private javax.swing.JPanel programIdentifier1;
    private javax.swing.JPanel programIdentifier3;
    private javax.swing.JPanel programIdentifier4;
    private javax.swing.JTable projectEdmerpTable;
    private javax.swing.JButton removeProject;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        group = validationPanel1.getValidationGroup();
        super.componentOpened();

        bt_editCruise.setEnabled(false);

        for (int i = 0; i < o_cruiseId.getItemCount(); i++) {
            CruiseBean cruise = (CruiseBean) o_cruiseId.getItemAt(i);
            if (cruise.getRealId().equals(actualProgram.getCruiseId())) {
                o_cruiseId.setSelectedIndex(i);
            }
        }

        o_programId.setText(actualProgram.getProgramId());
        // originatorListPrincipal.setSelectedItem(actualProgram.getOriginatorCode());
        originatorListSecondary.setSelectedItem(actualProgram.getOriginatorCode());
        o_principalInvestigator.setText(actualProgram.getPiName());
        o_description.setText(actualProgram.getDescription());
        o_collateCentreResult.setText(actualProgram.getOriginatorCode());
        projectTableModel.addEntities(actualProgram.getProjects());
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    ProgressHandle progr;

    private void postProgram() {
        if (formValidates()) {
            actualProgram = createProgramFromInput();
            if (actualProgram != null) {
                progr = ProgressHandleFactory.createHandle("Sending program info...");
                IResponseMessage response = null;
                AbstractProgramTopComponent.ProgramPoster tsk = new CreateProgramSetupTopComponent.ProgramPoster(progr, response);
                tsk.addListener(this);

                RequestProcessor.getDefault().post(tsk);

            }
        } else {
            Messaging.report("Form not valid. Verify it first", Message.State.BAD, this.getClass(), true);
        }
    }

    @Override
    public void checkValidation() {
        if (!formValidates()) {
            bt_editCruise.setEnabled(false);

        } else {
            bt_editCruise.setEnabled(true);
        }
    }

    @Override
    public void threadComplete(Runnable runner) {
        try {
            progr.finish();
            if (InfoBar.getInstance().getLatestState() == Message.State.GOOD) {
                this.close();
            }
        } catch (AssertionError | IllegalStateException e) {
            int a = 5;
        }
    }
}
