/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.naturalsciences.bmdc.ears.topcomponents;

import be.naturalsciences.bmdc.ears.topcomponents.tablemodel.ProjectTableModel;
import be.naturalsciences.bmdc.ears.entities.CruiseBean;
import be.naturalsciences.bmdc.ears.entities.IResponseMessage;
import be.naturalsciences.bmdc.ears.entities.Person;
import be.naturalsciences.bmdc.ears.entities.ProgramBean;
import be.naturalsciences.bmdc.ears.infobar.InfoBar;
import be.naturalsciences.bmdc.ears.utils.Message;
import be.naturalsciences.bmdc.ears.utils.Messaging;
import be.naturalsciences.bmdc.ears.utils.TaskListener;
import org.netbeans.api.progress.ProgressHandle;
import org.netbeans.api.progress.ProgressHandleFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.RequestProcessor;
import org.openide.util.lookup.Lookups;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//be.ac.mumm//EditProgramSetup//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EditProgramSetupTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER//ys
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "be.naturalsciences.bmdc.ears.topcomponents.EditProgramSetupTopComponent")
/*ys @ActionReference(path = "Menu/Window" , position = 3)*/

@TopComponent.OpenActionRegistration(
        displayName = "#CTL_EditProgramSetupAction",
        preferredID = "EditProgramSetupTopComponent"
)
@Messages({
    "CTL_EditProgramSetupAction=Edit Program",
    "CTL_EditProgramSetupTopComponent=EditProgramSetup Window",
    "HINT_EditProgramSetupTopComponent=This is a EditProgramSetup window"
})
public final class EditProgramSetupTopComponent extends AbstractProgramTopComponent implements TaskListener {

    private Lookup lookup;

    private static EditProgramSetupTopComponent instance;

    public EditProgramSetupTopComponent(ProgramBean program) {
        this();
        lookup = Lookups.singleton(program);
        this.actualProgram = program;
    }

    private EditProgramSetupTopComponent() {
        super();
        setName(Bundle.CTL_CreateProgramSetupTopComponent());
        setToolTipText(Bundle.HINT_CreateProgramSetupTopComponent());

        super.addProject = addProject;

        super.piOrganisationCountry = originatorListPrincipal;
        super.piOrganisationSecondary = piOrganisationCombobox;
        // super.cruiseComboBox = o_cruiseId;
        super.jPanel1 = jPanel1;
        super.jPanel2 = programProjectPanel;
        super.jPanelCollateCentre = piOrganisationPanel;
        super.jScrollPane1 = jScrollPane1;
        super.jScrollPane2 = jScrollPane2;
        super.jScrollPane3 = jScrollPane3;
        super.o_collateCentreResult = piOrganisationGreyTextField;
        super.descriptionTextField = descriptionTextField;
        super.piFirstNameTextField = firstNameTextbox;
        super.piLastNameTextField = lastNameTextbox;
        super.programIdTextField = o_programId;
        super.programIdentifier = programIdentifier;
        super.programIdentifier1 = programNamePanel;
        super.programIdentifier3 = piNamePanel;
        super.programIdentifier4 = programDescriptionPanel;
        super.projectEdmerpTable = projectEdmerpTable;
        super.removeProject = removeProject;
        instance = this;
    }

    @Override
    protected void __initComponents() {
        initComponents();
    }

    @Override
    public Lookup getLookup() {
        return lookup;
    }

    public static EditProgramSetupTopComponent getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        programProjectPanel = new javax.swing.JPanel();
        addProject = new javax.swing.JButton();
        removeProject = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projectEdmerpTable = new javax.swing.JTable();
        programNamePanel = new javax.swing.JPanel();
        o_programId = new javax.swing.JTextField();
        piOrganisationPanel = new javax.swing.JPanel();
        originatorListPrincipal = new javax.swing.JComboBox();
        piOrganisationCombobox = new javax.swing.JComboBox();
        piOrganisationGreyTextField = new javax.swing.JTextField();
        piNamePanel = new javax.swing.JPanel();
        firstNameTextbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lastNameTextbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        programDescriptionPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextField = new javax.swing.JTextArea();
        bt_editCruise = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        programProjectPanel.setBackground(new java.awt.Color(255, 255, 255));
        programProjectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programProjectPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(addProject, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.addProject.text")); // NOI18N
        addProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(removeProject, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.removeProject.text")); // NOI18N
        removeProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProjectActionPerformed(evt);
            }
        });

        projectEdmerpTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        projectEdmerpTable.setModel(new ProjectTableModel());
        projectEdmerpTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                projectEdmerpTableFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(projectEdmerpTable);

        javax.swing.GroupLayout programProjectPanelLayout = new javax.swing.GroupLayout(programProjectPanel);
        programProjectPanel.setLayout(programProjectPanelLayout);
        programProjectPanelLayout.setHorizontalGroup(
            programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programProjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProject, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeProject))
                .addContainerGap())
        );
        programProjectPanelLayout.setVerticalGroup(
            programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programProjectPanelLayout.createSequentialGroup()
                .addGroup(programProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programProjectPanelLayout.createSequentialGroup()
                        .addComponent(addProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeProject))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        programNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        programNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programNamePanel.border.title"))); // NOI18N
        programNamePanel.setPreferredSize(new java.awt.Dimension(695, 45));

        o_programId.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.o_programId.text")); // NOI18N
        o_programId.setEnabled(false);
        o_programId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_programIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout programNamePanelLayout = new javax.swing.GroupLayout(programNamePanel);
        programNamePanel.setLayout(programNamePanelLayout);
        programNamePanelLayout.setHorizontalGroup(
            programNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(o_programId, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        programNamePanelLayout.setVerticalGroup(
            programNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programNamePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(o_programId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        piOrganisationPanel.setBackground(new java.awt.Color(255, 255, 255));
        piOrganisationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.piOrganisationPanel.border.title"))); // NOI18N

        originatorListPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originatorListPrincipalActionPerformed(evt);
            }
        });

        piOrganisationCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piOrganisationComboboxActionPerformed(evt);
            }
        });

        piOrganisationGreyTextField.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.piOrganisationGreyTextField.text")); // NOI18N
        piOrganisationGreyTextField.setEnabled(false);
        piOrganisationGreyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piOrganisationGreyTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout piOrganisationPanelLayout = new javax.swing.GroupLayout(piOrganisationPanel);
        piOrganisationPanel.setLayout(piOrganisationPanelLayout);
        piOrganisationPanelLayout.setHorizontalGroup(
            piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piOrganisationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originatorListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piOrganisationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piOrganisationGreyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        piOrganisationPanelLayout.setVerticalGroup(
            piOrganisationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piOrganisationPanelLayout.createSequentialGroup()
                .addComponent(originatorListPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(piOrganisationCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(piOrganisationGreyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        piNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        piNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.piNamePanel.border.title"))); // NOI18N
        piNamePanel.setPreferredSize(new java.awt.Dimension(695, 45));

        firstNameTextbox.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.firstNameTextbox.text")); // NOI18N
        firstNameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextboxActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.jLabel1.text")); // NOI18N

        lastNameTextbox.setText(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.lastNameTextbox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout piNamePanelLayout = new javax.swing.GroupLayout(piNamePanel);
        piNamePanel.setLayout(piNamePanelLayout);
        piNamePanelLayout.setHorizontalGroup(
            piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        piNamePanelLayout.setVerticalGroup(
            piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piNamePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piNamePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(piNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piNamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addComponent(lastNameTextbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameTextbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        programDescriptionPanel.setBackground(new java.awt.Color(255, 255, 255));
        programDescriptionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.programDescriptionPanel.border.title"))); // NOI18N
        programDescriptionPanel.setPreferredSize(new java.awt.Dimension(695, 109));

        descriptionTextField.setColumns(20);
        descriptionTextField.setRows(5);
        jScrollPane2.setViewportView(descriptionTextField);

        javax.swing.GroupLayout programDescriptionPanelLayout = new javax.swing.GroupLayout(programDescriptionPanel);
        programDescriptionPanel.setLayout(programDescriptionPanelLayout);
        programDescriptionPanelLayout.setHorizontalGroup(
            programDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programDescriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        programDescriptionPanelLayout.setVerticalGroup(
            programDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        org.openide.awt.Mnemonics.setLocalizedText(bt_editCruise, org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.bt_editCruise.text")); // NOI18N
        bt_editCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editCruiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_editCruise))
                    .addComponent(piNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programDescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(piOrganisationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_editCruise, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(piNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piOrganisationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programDescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(904, Short.MAX_VALUE))
        );

        piOrganisationPanel.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(EditProgramSetupTopComponent.class, "EditProgramSetupTopComponent.piOrganisationPanel.AccessibleContext.accessibleName")); // NOI18N

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_editCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editCruiseActionPerformed
        // TODO add your handling code here:
        // Show Dialog...
        postProgram();
    }//GEN-LAST:event_bt_editCruiseActionPerformed

    private void firstNameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextboxActionPerformed

    private void piOrganisationGreyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piOrganisationGreyTextFieldActionPerformed
        // TODO add your handling code here:
        super.o_collateCentreResultActionPerformedP(evt);
    }//GEN-LAST:event_piOrganisationGreyTextFieldActionPerformed

    private void piOrganisationComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piOrganisationComboboxActionPerformed
        // TODO add your handling code here:
        super.collateCentreListSecondaryActionPerformedP(evt);
    }//GEN-LAST:event_piOrganisationComboboxActionPerformed

    private void originatorListPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originatorListPrincipalActionPerformed
        // TODO add your handling code here:
        super.collateCentreListPrincipalActionPerformedP(evt);
    }//GEN-LAST:event_originatorListPrincipalActionPerformed

    private void o_programIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_programIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_programIdActionPerformed

    private void projectEdmerpTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectEdmerpTableFocusLost
        // TODO add your handling code here:
        super.projectEdmerpTableFocusLostP(evt);
    }//GEN-LAST:event_projectEdmerpTableFocusLost

    private void removeProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProjectActionPerformed
        // TODO add your handling code here:
        super.removeProjectActionPerformedP(evt);
    }//GEN-LAST:event_removeProjectActionPerformed

    private void addProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectActionPerformed
        // TODO add your handling code here:
        super.addProjectActionPerformedP(evt);
    }//GEN-LAST:event_addProjectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProject;
    private javax.swing.JButton bt_editCruise;
    private javax.swing.JTextArea descriptionTextField;
    private javax.swing.JTextField firstNameTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastNameTextbox;
    private javax.swing.JTextField o_programId;
    private javax.swing.JComboBox originatorListPrincipal;
    private javax.swing.JPanel piNamePanel;
    private javax.swing.JComboBox piOrganisationCombobox;
    private javax.swing.JTextField piOrganisationGreyTextField;
    private javax.swing.JPanel piOrganisationPanel;
    private javax.swing.JPanel programDescriptionPanel;
    private javax.swing.JPanel programNamePanel;
    private javax.swing.JPanel programProjectPanel;
    private javax.swing.JTable projectEdmerpTable;
    private javax.swing.JButton removeProject;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        group = validationPanel1.getValidationGroup();
        super.componentOpened();
        programProjectPanel.setOpaque(false);
        piOrganisationPanel.setOpaque(false);
        programNamePanel.setOpaque(false);
        piNamePanel.setOpaque(false);
        programDescriptionPanel.setOpaque(false);
        bt_editCruise.setEnabled(false);
        o_programId.setText(actualProgram.getProgramId());
        // originatorListPrincipal.setSelectedItem(actualProgram.getOriginatorCode());
        Person pi = actualProgram.getPrincipalInvestigators().get(0);

        piOrganisationCombobox.setSelectedItem(pi.organisationCode);
        firstNameTextbox.setText(pi.firstName);
        lastNameTextbox.setText(pi.lastName);
        descriptionTextField.setText(actualProgram.getDescription());
        o_collateCentreResult.setText(pi.organisationCode);
        projectTableModel.addEntities(actualProgram.getProjects());
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    ProgressHandle progr;

    private void postProgram() {
        if (formValidates()) {
            actualProgram = createProgramFromInput();
            if (actualProgram != null) {
                progr = ProgressHandleFactory.createHandle("Sending program info...");
                IResponseMessage response = null;
                AbstractProgramTopComponent.ProgramModifier tsk = new CreateProgramSetupTopComponent.ProgramModifier(progr, response);
                tsk.addListener(this);

                RequestProcessor.getDefault().post(tsk);

            }
        } else {
            Messaging.report("Form not valid. Verify it first", Message.State.BAD, this.getClass(), true);
        }
    }

    @Override
    public void checkValidation() {
        if (!formValidates()) {
            bt_editCruise.setEnabled(false);

        } else {
            bt_editCruise.setEnabled(true);
        }
    }

    @Override
    public void threadComplete(Runnable runner) {
        progr.finish();
    }

    @Override
    public void resultChanged(LookupEvent arg0) {
    }
}
